### ISSUE TITLE
Javascript error on IE causing products not to load

### ISSUE THREAD

**Issue by andrewdrake** [shopwp/wp-shopify#111]
See screenshot

![image](https://user-images.githubusercontent.com/2742557/77505755-1dba2e00-6eb8-11ea-8deb-3ad0b044243a.png)

**Comment by arobbins** [comment]
@andrewdrake 

Hey there, the current version of WP Shopify does not support IE 11 or below. 

I'm looking to add support for IE 11 in the upcoming 3.0 version which should be out around the end of April.

**Comment by andrewdrake** [comment]
Thanks, sorry just saw this from a while ago and will close now
